### PR TITLE
Fixes #1048: fix execution of search method without query string

### LINKED ISSUE #1048: search keeps on executing with no search query
The search method of SearchServlet class keeps on executing again and again even without any search query.

Thus the same lines of code keeps in executing to get solution for search query -> "" , thus leading to no solution.This can be checked by logging in this search method (in org/loklak/api/search/SearchServlet.java/SearchServlet.search()).

### PR DESCRIPTION
**Pull request by vibhcool**
Same lines of code to search a query keeps on executing even if there is no query. 
This fix prevents running of same lines of code without search query again and again.

### CODE REVIEW

**Comment by yukiisbored** [comment]
@vibhcool Please create an issue first.

**Comment by vibhcool** [comment]
this PR fixes issue #1048,
open for review :)

**Comment by vibhcool** [comment]
@daminisatya made the changes :)

File: src/org/loklak/api/search/SearchServlet.java [hunk 1]
```diff
@@ -6,12 +6,12 @@
  *  modify it under the terms of the GNU Lesser General Public
  *  License as published by the Free Software Foundation; either
  *  version 2.1 of the License, or (at your option) any later version.
- *
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 2]
```diff
@@ -6,12 +6,12 @@
  *  modify it under the terms of the GNU Lesser General Public
  *  License as published by the Free Software Foundation; either
  *  version 2.1 of the License, or (at your option) any later version.
- *  
+ *
  *  This library is distributed in the hope that it will be useful,
  *  but WITHOUT ANY WARRANTY; without even the implied warranty of
  *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  *  Lesser General Public License for more details.
- *
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 3]
```diff
@@ -63,7 +63,7 @@
     private final static String SEARCH_MAX_LOCALHOST_COUNT_NAME = "search.count.max.localhost";
 
     private final static int SEARCH_CACHE_THREASHOLD_TIME = 3000;
-
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 4]
```diff
@@ -106,18 +109,18 @@ public static Timeline search(final String protocolhostportstub, final String qu
         //System.out.println(parser.text());
         return tl;
     }
-
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 5]
```diff
@@ -106,18 +109,18 @@ public static Timeline search(final String protocolhostportstub, final String qu
         //System.out.println(parser.text());
         return tl;
     }
-    
+
     @Override
     protected void doPost(final HttpServletRequest request, final HttpServletResponse response) throws ServletException, IOException {
         doGet(request, response);
     }
-
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 6]
```diff
@@ -106,18 +109,18 @@ public static Timeline search(final String protocolhostportstub, final String qu
...
         doGet(request, response);
     }
-    
+
     @Override
     protected void doGet(final HttpServletRequest request, final HttpServletResponse response) throws ServletException, IOException {
         final long start = System.currentTimeMillis();
         final Query post = RemoteAccess.evaluate(request);
         final ClientIdentity identity = AbstractAPIHandler.getIdentity(request, response, post);
-
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 7]
```diff
@@ -184,7 +187,7 @@ public void run() {
                         DAO.log(request.getServletPath() + " scraping with query: " + scraper_query);
                         Timeline twitterTl = DAO.scrapeTwitter(post, scraper_query, order, timezoneOffsetf, true, timeout, true);
                         count_twitter_new.set(twitterTl.size());
-                        tl.putAll(QueryEntry.applyConstraint(twitterTl, tokens, false)); // pre-localized results are not filtered with location constraint any more
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 8]
```diff
@@ -243,7 +246,7 @@ public void run() {
                 DAO.log(request.getServletPath() + " scraping with query: " + scraper_query);
                 Timeline twitterTl = DAO.scrapeTwitter(post, scraper_query, order, timezoneOffset, true, timeout, true);
                 count_twitter_new.set(twitterTl.size());
-                tl.putAll(QueryEntry.applyConstraint(twitterTl, tokens, false)); // pre-localized results are not filtered with location constraint any more
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 9]
```diff
@@ -269,16 +272,16 @@ public void run() {
                 post.recordEvent("backend_time", System.currentTimeMillis() - start);
 
             }
-
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 10]
```diff
@@ -269,16 +272,16 @@ public void run() {
                 post.recordEvent("backend_time", System.currentTimeMillis() - start);
 
             }
-    
+
             // check the latest user_ids
             DAO.announceNewUserId(tl);
-
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 11]
```diff
@@ -269,16 +272,16 @@ public void run() {
...
             // check the latest user_ids
             DAO.announceNewUserId(tl);
-            
+
             hits.put("count_twitter_all", count_twitter_all.get());
             hits.put("count_twitter_new", count_twitter_new.get());
             hits.put("count_backend", count_backend.get());
             hits.put("cache_hits", cache_hits.get());
         }
-
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 12]
```diff
@@ -317,10 +320,10 @@ public void run() {
                 // we silently do nothing here and return what we listed so far
             }
             m.put("statuses", statuses);
-
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 13]
```diff
@@ -317,10 +320,10 @@ public void run() {
                 // we silently do nothing here and return what we listed so far
             }
             m.put("statuses", statuses);
-            
+
             // aggregations
             m.put("aggregations", aggregations);
-
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

File: src/org/loklak/api/search/SearchServlet.java [hunk 14]
```diff
@@ -357,7 +360,7 @@ public void run() {
             }
             String rss = feed.toString();
             //System.out.println("feed has " + feed.size() + " entries");
-
```
Comment (yukiisbored) [inline src/org/loklak/api/search/SearchServlet.java]: Please revert this line, it's not part of the issue. If you want to do some house-keeping or cleaning, please create a new PR and Issue for it.

**Comment by vibhcool** [comment]
@yukiisbored fixed the pr :)

**Comment by yukiisbored** [comment]
@vibhcool Fix the codacy issue, please. I know it's pretty weird but it does have a point.

**Comment by vibhcool** [comment]
@codacy made the suggested changes :P :D

**Comment by yukiisbored** [comment]
@daminisatya please approve or revise review

**Comment by vibhcool** [comment]
thank you :)
