### PR TITLE
Use java.net.URL to build relative URL in ClientConnection

### LINKED ISSUE #1179: URL Unshortener gives incorrect URL for relative URLs in meta tag if ending with /
- Issue type: Bug report

### Short description
The meta tag extractor fails with relative URL with the original address ending with `/`.
For example - 
Original: `http://yacy.net/`
Meta redirect URL: `en/index.html`
Actual URL fetched: `en/index.html`
Expected: `http://yacy.net/en/index.html`

### PR DESCRIPTION
**Pull request by singhpratyush**
### Short description

Fixes #1179.

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

File: src/org/loklak/http/ClientConnection.java [hunk 1]
```diff
@@ -363,8 +364,9 @@ public static String getRedirect(String urlstring, boolean useAuthentication, bo
                     if (debugLog) {
                         DAO.log("Fetched Meta redirect URL for " + urlstring + " : " + metaURL);
                     }
-                    if (!metaURL.startsWith("http") && !urlstring.endsWith("/")) {
-                        return urlstring + "/" + metaURL;
+                    if (!metaURL.startsWith("http")) {
+                        URL u = new URL(new URL(urlstring), metaURL);
+                        return u.toString();
```
Comment (vibhcool) [inline src/org/loklak/http/ClientConnection.java]: Why shall we use url as string is converted to url and then to string.
URL object is used to manipulate url, get it's parts, etc. what is the use here?

Comment (singhpratyush) [inline src/org/loklak/http/ClientConnection.java]: It is used to build a complete URL from two parts - base and relative.
For example, when the base URL is `http://yacy.net` and the relative URL is `en/index.html`, it would give `http://yacy.net/en/index.html`.

It will also take care of other stuff - 
* `http://yacy.net/` + `/en/index.html` = `http://yacy.net/en/index.html` (take care of slashes).
* `http://a.com/b/c` + `../d` = `http://a.com/b/d`.

Comment (vibhcool) [inline src/org/loklak/http/ClientConnection.java]: got it, i missed it 😅

**Comment by singhpratyush** [comment]
@SarishiNoHara @kavithaenair @djmgit @Achint08 @hemantjadon: Please review.

**Comment by SarishiNoHara** [comment]
LGTM
