### PR TITLE
Fix #1070: Strings must use doublequote. (quotes), no-use-before-define

### LINKED ISSUE #1070: Improve Code Quality following the Codacy Metric
- Issue type: Bug report 

### Short description

[Codacy][issues] shows a lot of issues with the current code.
Remove such an issue.

### Steps to follow

1. Go to the [Codacy issues][issues], you may sort them by file.
2. Remove an issue in the code without changing the behavior of the code.
3. commit:
  - Reference this issue
  - link to the codacy issue in the extended description (two newlines)
4. Create a pull-request to see if the issue was resolved and the codacy count increased.

### Usecase

Improving the code quality not only speeds up development.
It is also a great way for new contributors to enter the project (setup, workflow, community) without worrying too much about the complexity.

[issues]: https://www.codacy.com/app/sudheesh1995/loklak_server/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbIkVycm9yIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltudWxsXX1d

### PR DESCRIPTION
**Pull request by Carrein**
Fix for codacy issues in #1070.

### CODE REVIEW

**Comment by singhpratyush** [comment]
Please remove Visual Studio files.

**Comment by vibhcool** [comment]
Congo for your first PR :+1:

But need some corrections :-
 - Since you have fixed a part of issue, so please replace 'fix #1070' with something like 'fixes a part of #1070' in commit names and PR name as it leads to closing of issue automatically.
 - Try not to create and close multiple PR's , create one, and fix it if you run into trouble.
 - squash your 3 commits to one.

Just land in the loklak/loklak gitter channel for any query or issue you face

File: html/apps/forgotpassword/js/passwordrecovery.js [hunk 1]
```diff
@@ -2,7 +2,7 @@ $(document).ready(function()
 {
     var emailerr = false, session = true;
 
-    $('#submit').click(function(){
+    $("#submit").click(function(){
         checkEmpty();
         if(emailerr){
             $('#status-box').text("Please fill email");
```
Comment (djmgit) [inline html/apps/forgotpassword/js/passwordrecovery.js]: I guess $('#status-box') should be $("status-box")

File: html/apps/forgotpassword/js/passwordrecovery.js [hunk 2]
```diff
@@ -2,50 +2,50 @@ $(document).ready(function()
...
+            $("#emailfield").text("");
+        }
+    }
+
+    $("#submit").click(function(){
         checkEmpty();
         if(emailerr){
-            $('#status-box').text("Please fill email");
+            $("#status-box").text("Please fill email");
         } else{
```
Comment (kavithaenair) [inline html/apps/forgotpassword/js/passwordrecovery.js]: Follow the codacy matrix standard and fix the indentation.
instead of " } else{ " correct it as " } else { "

**Comment by mariobehling** [comment]
Ok, thanks. I am merging this and we follow up in https://github.com/loklak/loklak_server/issues/1144
