### PR TITLE
Unshorten URL until applicable

### LINKED ISSUE #1297: Redirect unshortening service makes message collection much slower
- Issue type: Bug report

### Short description

Parent issue: #1296.

Due to making more number of requests before achieving a final, shortened URL, the time taken to collect a complete Tweet is very much. This, therefore, decreases the message collection rate by a significant factor.

It was introduced in #1122.

### PR DESCRIPTION
**Pull request by singhpratyush**
### Short description

Fixes #1297.

URL redirect unshortener would not keep unshortening URLs until it has reached some final URL. It will do so only until there are chances of URL being trackable.

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [x] Reviewed this pull request by an authorized contributor.
- [x] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by singhpratyush** [comment]
@Achint08 @djmgit @hemantjadon @kavithaenair @SKrPl @vibhcool: Please review.

File: src/org/loklak/harvester/RedirectUnshortener.java [hunk 1]
```diff
@@ -6,12 +6,12 @@
  *  modify it under the terms of the GNU Lesser General Public
  *  License as published by the Free Software Foundation; either
  *  version 2.1 of the License, or (at your option) any later version.
- *  
+ *
```
Comment (sudheesh001) [inline src/org/loklak/harvester/RedirectUnshortener.java]: Unwanted change This is a standard template that gets prepended to the start of the file and needn't be modified.

File: src/org/loklak/harvester/RedirectUnshortener.java [hunk 2]
```diff
@@ -6,12 +6,12 @@
...
  *  This library is distributed in the hope that it will be useful,
  *  but WITHOUT ANY WARRANTY; without even the implied warranty of
  *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  *  Lesser General Public License for more details.
- *  
+ *
```
Comment (sudheesh001) [inline src/org/loklak/harvester/RedirectUnshortener.java]: same here.

File: src/org/loklak/harvester/RedirectUnshortener.java [hunk 3]
```diff
@@ -57,7 +57,7 @@
         "flip.it",
         "lnkd.in"
     };
```
Comment (sudheesh001) [inline src/org/loklak/harvester/RedirectUnshortener.java]: Is the string of working hosts ever going to get updated on a successful unshortening?

File: test/org/loklak/harvester/RedirectUnshortenerTest.java [hunk 4]
```diff
@@ -21,7 +21,7 @@ public void testRedirectUnshortener() {
         shortlinkMap.put("http://ow.ly/P9SX30ddSTI", "https://github.com/loklak/loklak_server/issues/1284");
         shortlinkMap.put("http://bit.do/blog-fossasia", "http://blog.fossasia.org/");
         shortlinkMap.put("http://fb.me/4lcXZsyyO", "https://www.facebook.com/permalink.php?story_fbid=1550262581900846&id=1381813572079082");
-        shortlinkMap.put("http://wp.me/sf2B5-shorten", "https://en.blog.wordpress.com/2009/08/14/shorten/");
+        shortlinkMap.put("http://wp.me/sf2B5-shorten", "http://en.blog.wordpress.com/2009/08/14/shorten/");
```
Comment (sudheesh001) [inline test/org/loklak/harvester/RedirectUnshortenerTest.java]: the shortened URL redirects to `https://`, Is there a reason why this was changed to `http`

File: src/org/loklak/harvester/RedirectUnshortener.java (hunk 1 above)
Comment (singhpratyush) [inline src/org/loklak/harvester/RedirectUnshortener.java]: These changes are introduced by IDE due to [`.editorconfig`](https://github.com/loklak/loklak_server/blob/development/.editorconfig) file and are made to many other files too.

File: src/org/loklak/harvester/RedirectUnshortener.java (hunk 3 above)
Comment (singhpratyush) [inline src/org/loklak/harvester/RedirectUnshortener.java]: No, they will not be updated.

File: test/org/loklak/harvester/RedirectUnshortenerTest.java (hunk 4 above)
Comment (singhpratyush) [inline test/org/loklak/harvester/RedirectUnshortenerTest.java]: Earlier (before this patch), the redirections were resolved until a final URL is reached. But it isn't required as the prime reason behind resolving redirects is to avoid tracking by other web services.

Once the URL is no longer a threat to anonymity, there is no need to resolve redirects any further as it will take time for no reason.

In this case, `http://en.blog...` is not a trackable URL so we'll not get redirected to `https://en.blog...`, so I changed it here.

File: src/org/loklak/harvester/RedirectUnshortener.java (hunk 3 above)
Comment (sudheesh001) [inline src/org/loklak/harvester/RedirectUnshortener.java]: From the code I can see that it won't be, I am more over asking something to peek curiosity like, wouldn't that be a nicer thing.

File: test/org/loklak/harvester/RedirectUnshortenerTest.java (hunk 4 above)
Comment (sudheesh001) [inline test/org/loklak/harvester/RedirectUnshortenerTest.java]: No I don't seem to understand the statement, based on a URL shortened how can you say that it is a threat to anonymity or that it is a trackable or untrackable URL? if i have an URL which is http://b.ly vs https://b.ly where is the anonymity coming into place?

At what stage of URL redirect solution do you decide that the URL is not `anonymized`. Either way when your request hits the URL it will be tracked by who so ever does it. I don't see anonymity threats anywhere here.

My question is why does this test have `http://` instead of `https://` when `https://` works? Does the test fail when it's https?

Comment (singhpratyush) [inline test/org/loklak/harvester/RedirectUnshortenerTest.java]: > My question is why does this test have `http://` instead of `https://` when `https://` works?

To explain this, let me take an example - 
`http://bit.ly/xyz` -> `http://something.new` -> `https://something.new`

Now, the URL unshortener would request `http://bit.ly/xyz` and get a `30X` response code asking for a redirect to `http://something.new`. Now, this URL is not `isApplicable()`, so the unshortener would not request this URL (and hence wouldn't get redirected to `https://something.new`). And when a user requests for `http://something.new` (after getting the URL from loklak's API), his browser redirects to `https://something.new`.

This would save loklak at least one HTTP request (maybe `https://something.new` -> `http://something.newer` -> `https://something.newer`) before finalizing a Tweet.

> Does the test fail when it's https?

After this change, yes.

> At what stage of URL redirect solution do you decide that the URL is not `anonymized`.

If it `isApplicable()`, it needs to be unshortened.


Just to mention, the [previous version of `RedirectUnshortener`](https://github.com/loklak/loklak_server/blob/ef587d75cf40c258e7996454c2a1838e599b618e/src/org/loklak/harvester/RedirectUnshortener.java#L80) also used this logic.

File: src/org/loklak/harvester/RedirectUnshortener.java (hunk 3 above)
Comment (singhpratyush) [inline src/org/loklak/harvester/RedirectUnshortener.java]: I guess it would be better, but I don't see the two arrays having any impact on the code (or why are they two different arrays in the first place). So juggling a service from one array to other won't make a difference I guess.

File: test/org/loklak/harvester/RedirectUnshortenerTest.java (hunk 4 above)
Comment (vibhcool) [inline test/org/loklak/harvester/RedirectUnshortenerTest.java]: IMHO you could also keep both the present method to get the exact url and the applicable method and use this one.

Comment (singhpratyush) [inline test/org/loklak/harvester/RedirectUnshortenerTest.java]: @hemantjadon: I never mentioned that `http` or `https` has anything to do with anonymity. I was just saying that we do not need to resolve a URL from `http` to `https` if it isn't from any url shortening service (which generally maintain stats about who is visiting the link, from where, interests, etc.).

**Comment by singhpratyush** [comment]
I think that the purpose of this change needs to be clarified. This PR aims to reduce the number of HTTP requests that are required to be made before finalising a Tweet. And there are some redirects that we do not need to perform, hence, we can skip the URLs if they are not applicable for unshortening.

File: test/org/loklak/harvester/RedirectUnshortenerTest.java (hunk 4 above)
Comment (hemantjadon) [inline test/org/loklak/harvester/RedirectUnshortenerTest.java]: @singhpratyush Okay got it 👍
