### PR TITLE
Fixes #1566. Fix Github profile search console service.

### LINKED ISSUE #1566: Empty response for github profile search using console service.
- Issue type: Bug report

### Short description
Response from
[https://localhost:9000/api/console.json?q=SELECT * FROM githubProfile WHERE profile='kapillamba4';](http://localhost:9000/api/console.json?q=SELECT%20*%20FROM%20githubProfile%20WHERE%20profile=%27kapillamba4%27;)
is this:
image

### PR DESCRIPTION
**Pull request by kapillamba4**
Fixes #1566.
### Short description
I have:
- [X] There is a corresponding issue for this pull request.
- [X] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [X] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

https://api.myjson.com/bins/dy42d
Removed parseInt calls because it fails with NumberFormatException if count > 1000, for example in case of https://github.com/torvalds, the followers count is 68.2K currently.

### CODE REVIEW

File: src/org/loklak/api/search/ConsoleService.java [hunk 1]
```diff
@@ -214,7 +214,9 @@ public String getAPIPath() {
         });
         dbAccess.put(Pattern.compile("SELECT +?(.*?) +?FROM +?githubProfile +?WHERE +?profile ??= ??'(.*?)' ??;"), matcher -> {
             BaseScraper githubScrape = new GithubProfileScraper(matcher.group(2));
-            SusiThought json = new SusiThought(githubScrape.getData());
+            JSONObject obj = githubScrape.getData();
```
Comment (vibhcool) [inline src/org/loklak/api/search/ConsoleService.java]: `Post` object shall be used here instead of `JSONObject`. Check it!!

**Comment by kapillamba4** [comment]
Updated the PR 👍

**Comment by kapillamba4** [comment]
Fixed failing QuoraScrapperTest because of different image url's for same image:
https://qph.ec.quoracdn.net/main-thumb-24728160-200-igibbfdmibqxdtrjlrdnejpvjqepxpnn.jpeg
https://qph.fs.quoracdn.net/main-thumb-24728160-200-igibbfdmibqxdtrjlrdnejpvjqepxpnn.jpeg

Now comparing url path after "https://qph.ec.quoracdn.net" instead of comparing complete url.
