### PR TITLE
Fixes #1555. Change user-agent in request headers to fix failing youtube tests.

### LINKED ISSUE #1555: YoutubeScraper test fails
- Issue type: Bug report

### Short description

Here is the log from build - 

```java
org.loklak.TestRunner > org.loklak.harvester.YoutubeScraperTest.parseFromInputStreamTest FAILED
    java.lang.AssertionError: 
    Expected: is "[\"Iggy Azalea - Team (Explicit) - YouTube\"]"
         but: was "[\"YouTube\"]"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.loklak.harvester.YoutubeScraperTest.parseFromInputStreamTest(YoutubeScraperTest.java:39)
```

### Environment

 - Operating system: Ubuntu 16.04LTS
 - Software version: 8d521a8461ef65a4b4ab5c8b90d5f5b43d0fbf23
 - Software source: Github repository

### Steps to reproduce

1. Get even with `loklak:development`.
2. `./gradlew build -i`
3. Look at the logs

### Expected behaviour
The test should pass.

### Actual behaviour
Test fails.

### PR DESCRIPTION
**Pull request by kapillamba4**
Fixes #1555
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

Build is successfully now:
image

Response from
``` 
$ curl -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36" https://www.youtube.com/watch?v=KVGRN7Z7T1A
```
is https://paste.ubuntu.com/26479210/

Response from 
```
$ curl -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36" https://www.youtube.com/watch?v=KVGRN7Z7T1A
```
is https://paste.ubuntu.com/26472474/

### CODE REVIEW

File: src/org/loklak/http/ClientConnection.java [hunk 1]
```diff
@@ -78,14 +78,14 @@
  */
 public class ClientConnection {
 
-    public static String USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36";
+    public static String USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36";
```
Comment (singhpratyush) [inline src/org/loklak/http/ClientConnection.java]: :tada:
