### PR TITLE
Remove hash from hashtag list

### LINKED ISSUE #1457: Hash symbol appended in front of hashtag set linked to a status and to the aggregations
- Issue type: Bug report

### Short description

The backend is returning all the entities with hash symbol appended, at the start of every string of hashtag set linked to a status and to the aggregations.
This behaviour is unexpected.

### PR DESCRIPTION
**Pull request by singhpratyush**
### Short description

Fixes #1457.

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

File: src/org/loklak/objects/MessageEntry.java [hunk 1]
```diff
@@ -57,7 +57,7 @@
     // left boundary must be space since the @ is itself a boundary
     public final static Pattern USER_PATTERN = Pattern.compile("(?:[ (]|^)(@..*?)(?:\\b|$)");
     // left boundary must be a space since the # is itself a boundary
-    final static Pattern HASHTAG_PATTERN = Pattern.compile("(?:[ (]|^)(#..*?)(?:\\b|$)");
+    final static Pattern HASHTAG_PATTERN = Pattern.compile("(?:[ (]|^)#(..*?)(?:\\b|$)");
```
Comment (sudheesh001) [inline src/org/loklak/objects/MessageEntry.java]: Any tests? Doesn't keeping the `#` outside mandate that the hash is available in the pattern?

It'd always be better to have a test to pass and fail these patterns, that'd give a detailed reason as to why this change in regex is needed.

Comment (vibhcool) [inline src/org/loklak/objects/MessageEntry.java]: @sudheesh001 There isn't a bug in hashtags, the hashtags work fine, but Loklak Search team suggested that hashtags strings are more useful than hashtags with `#` symbol. https://github.com/loklak/loklak_server/issues/1457#issuecomment-322570756
