### PR TITLE
fix #1143: Fix NumberException in YoutubeScraper

### LINKED ISSUE #1143: YoutubeScraper fails with NumberFormatException
After merge of https://github.com/loklak/loklak_server/pull/1106/ the YoutubeScraper fails:

```
java.lang.NumberFormatException: For input string: "4,8Mio."
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.loklak.harvester.YoutubeScraper.parseNumber(YoutubeScraper.java:210)
	at org.loklak.harvester.YoutubeScraper.parseVideo(YoutubeScraper.java:137)
	at org.loklak.harvester.YoutubeScraperTest.whneTryParseVideoFromBufferedReaderShouldCheckThatIsGoodJsonObjectReturn(YoutubeScraperTest.java:40)
```

### PR DESCRIPTION
**Pull request by vibhcool**
fixes issue #1143

This is patch that considers the fact that a number in youtube can also be alphanumerical like 4.4M (4.4 million) or like a number like 123,123,345. So it considers just as a number

### CODE REVIEW

**Comment by vibhcool** [comment]
I have little messed up...., This is not open for review

**Comment by vibhcool** [comment]
Open for review :smile:

**Comment by singhpratyush** [comment]
Does 4.4M need to be converted to 4,400,000?

**Comment by kavithaenair** [comment]
@vibhcool can you please attach a screenshot of the final output? Try giving the input as mentioned in the issue #1143 .

**Comment by vibhcool** [comment]
@singhpratyush 
the numbers on youtube we see can be of following formats:-
1) 123,123,312
2) 3
3) 4K meaning 4000
4) 5.3M .....etc
this fix checks them, get them and put them in JsonObject

**Comment by vibhcool** [comment]
@kavithaenair to reproduce the error , Steps:-
1) comment this line -> https://github.com/loklak/loklak_server/blob/da1bb1089d29e2f079089968572340d4f567fafe/src/org/loklak/harvester/TwitterScraper.java#L188
(to prevent this flood the terminal, fixed this in PR #1153) 

2) run this command -> `./gradlew build`

3) run `bin/test.sh`
check the output at development branch with this

File: src/org/loklak/harvester/YoutubeScraper.java [hunk 1]
```diff
@@ -205,9 +203,14 @@ public static JSONObject parseVideo(final BufferedReader br) throws IOException
         return json;
     }
     
-    private static long parseNumber(String n) throws NumberFormatException {
-        String withoutSpaces = CharMatcher.WHITESPACE.removeFrom(n);
-        return Long.parseLong(withoutSpaces);
+    private static String parseValue(String n) {
+        String number_value = CharMatcher.WHITESPACE.removeFrom(n);
+        Pattern number_format = Pattern.compile("((\\d)\\d{0,2})(,?\\d{3})*(\\.[\\d]+)?([MBK]?)");
```
Comment (singhpratyush) [inline src/org/loklak/harvester/YoutubeScraper.java]: This may become `static` member of the class.

**Comment by singhpratyush** [comment]
> this fix checks them, get them and put them in JsonObject

Is it not required here to convert the number to numeric-only value, like I mentioned in previous comment?

File: src/org/loklak/harvester/YoutubeScraper.java (hunk 1 above)
Comment (vibhcool) [inline src/org/loklak/harvester/YoutubeScraper.java]: this is static member of class, I didn't understand what you are suggesting :sweat_smile:

**Comment by vibhcool** [comment]
youtube outputs some numbers like no. of subscriptions as 2M instead of it's exact value 2,353,367 , and so this 2M can be output like 2 million, 2M or 2000000 , but this numeric value isn't exact value and doesn't seem to be nice to as it is incorrect.

File: src/org/loklak/harvester/YoutubeScraper.java (hunk 1 above)
Comment (singhpratyush) [inline src/org/loklak/harvester/YoutubeScraper.java]: Since the variable `pattern_format` will be same every time, you can add it to the top of the class as a `private static` member.

File: src/org/loklak/harvester/YoutubeScraper.java [hunk 2]
```diff
@@ -134,28 +135,25 @@ public static JSONObject parseVideo(final BufferedReader br) throws IOException
...
                     String subscriber_string = parseProp(input, p, "title");
                     if (subscriber_string == null) continue;
-                    json.put("youtube_subscriber", parseNumber(subscriber_string));
+                    json.put("youtube_subscriber", parseValue(subscriber_string));
                     continue;
                 }
                 if (input.indexOf("\"like this") > 0 && (p = input.indexOf("yt-uix-button-content")) >= 0) {
                     String likes_string = parseTag(input, p);
-                    json.put("youtube_likes", parseNumber(likes_string));
+                    json.put("youtube_likes", parseValue(likes_string));
```
Comment (Achint08) [inline src/org/loklak/harvester/YoutubeScraper.java]: Hey @vibhcool . number of likes are always in numbers format . Only subscribers are shown in M,B,K format.  You can remove this.

File: src/org/loklak/harvester/YoutubeScraper.java [hunk 3]
```diff
@@ -134,28 +135,25 @@ public static JSONObject parseVideo(final BufferedReader br) throws IOException
...
                     continue;
                 }
                 if (input.indexOf("\"dislike this") > 0 && (p = input.indexOf("yt-uix-button-content")) >= 0) {
                     String dislikes_string = parseTag(input, p);
-                    json.put("youtube_dislikes", parseNumber(dislikes_string));
+                    json.put("youtube_dislikes", parseValue(dislikes_string));
```
Comment (Achint08) [inline src/org/loklak/harvester/YoutubeScraper.java]: Same goes for this.

File: src/org/loklak/harvester/YoutubeScraper.java [hunk 4]
```diff
@@ -134,28 +135,25 @@ public static JSONObject parseVideo(final BufferedReader br) throws IOException
...
                 if ((p = input.indexOf("watch-view-count")) >= 0) {
                     String viewcount_string = parseTag(input, p);
                     if (viewcount_string == null) continue;
                     viewcount_string = viewcount_string.replace(" views", "");
                     if (viewcount_string.length() == 0) continue;
-                    long viewcount = 0;
-                    // if there are no views, there may be a string saying "No". But this is done in all languages, so we just catch a NumberFormatException
-                    try {viewcount = parseNumber(viewcount_string);} catch (NumberFormatException e) {}
-                    json.put("youtube_viewcount", viewcount);
+                    json.put("youtube_viewcount", viewcount_string);
```
Comment (Achint08) [inline src/org/loklak/harvester/YoutubeScraper.java]: Same goes for this.

File: src/org/loklak/harvester/YoutubeScraper.java (hunk 1 above)
Comment (singhpratyush) [inline src/org/loklak/harvester/YoutubeScraper.java]: The regex will also accept values like `123,45` as `123` and `45`, which is not acceptable. Please fix it.

Also, the regex can be simplified. Please look into it.

Comment (Achint08) [inline src/org/loklak/harvester/YoutubeScraper.java]: Regular expression is not working correctly for all the corner cases as well. Recheck it once.

Comment (vibhcool) [inline src/org/loklak/harvester/YoutubeScraper.java]: @singhpratyush if we set it as private static member, it will consume memory for complete lifecycle of the YoutubeScraper oubject. It is used only in 1 method, So maybe local declaration suits it

Comment (vibhcool) [inline src/org/loklak/harvester/YoutubeScraper.java]: @singhpratyush  123,45 isn't valid number, commas are put at the gap of 3 digits in numbers in internamtional system. 
Seeing for simplification :smile: 

@Achint08 could you share the cases where regex isn't working.

Comment (singhpratyush) [inline src/org/loklak/harvester/YoutubeScraper.java]: > 123,45 isn't valid number

exactly, but it will get accepted by the regex as two discrete matches - `123` and `45`.

Comment (vibhcool) [inline src/org/loklak/harvester/YoutubeScraper.java]: @singhpratyush the regex seems to be perfect :sweat_smile:

Comment (singhpratyush) [inline src/org/loklak/harvester/YoutubeScraper.java]: @vibhcool: The regex you mentioned is 
```
((\d)\d{0,2})(,?\d{3})*(\.[\d]+)?([MBK]?)
```
If we try to parse `123,45`, here's what happens - 
```
  1 -> \d
 23 -> \d{2}
,45 -> No match, fall back, check for acceptance of previous substring
123 -> passes as \d\d{2}
  , -> No match, skip
  4 -> \d
  5 -> \d{1}
EOF -> 45 passes as \d\d{1}
```

So, we have two matches for `123,45`. What went wrong? The fact that your regex tries to match any possible substring. A better solution would be
```
^((\d)\d{0,2})(,?\d{3})*(\.[\d]+)?([MBK]?)$
```
This will do things fine, but regex can still be a lot simpler - 
```
^\d{1,3}(,\d{3})*(\.\d+)?[MBK]$
```
Breaking it down,
```
        ^ - Start of string
  \d{1,3} - X or XX or XXX
(,\d{3})* - ,XXX repeated zero or more times
 (\.\d+)? - .X or .XX or .XXX ...
   [MBK]? - M or B or K occurs 0 or 1 times
        $ - End of string
```

regex101.com is a goog website.

Comment (Achint08) [inline src/org/loklak/harvester/YoutubeScraper.java]: @vibhcool  Hey!! Regular expression is not even giving match for 10M currently. 
As given by @singhpratyush  , `^\d{1,3}(,\d{3})*(\.\d+)?[MBK]?$` works fine. :)
