### PR TITLE
Fixes 1316: StackOverflow error due to toString method

### LINKED ISSUE #1316: StackOverflow error due to toString method
- Issue type: Bug report

There is stackoverflow error in loklak logs

error: https://gist.github.com/vibhcool/937256055421222f7002db2f7d09a26b

This error appears occasionally in logs.

### PR DESCRIPTION
**Pull request by vibhcool**
This PR fixes issue #1316

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

File: src/org/loklak/objects/MessageEntry.java [hunk 1]
```diff
@@ -564,8 +564,8 @@ public JSONObject toJSON() {
     public Post toJSON(final UserEntry user, final boolean calculatedData, final int iflinkexceedslength, final String urlstub) {
 
         // tweet data
-        this.put(AbstractObjectEntry.TIMESTAMP_FIELDNAME, utcFormatter.print(getTimestampDate().getTime()));
-        this.put(AbstractObjectEntry.CREATED_AT_FIELDNAME, utcFormatter.print(getCreatedAt().getTime()));
+        this.put(AbstractObjectEntry.TIMESTAMP_FIELDNAME, AbstractObjectEntry.utcFormatter.print(getTimestampDate().getTime()));
```
Comment (singhpratyush) [inline src/org/loklak/objects/MessageEntry.java]: @vibhcool: Could you please tell a bit about why was the issue there and how would this solve it?

Comment (vibhcool) [inline src/org/loklak/objects/MessageEntry.java]: @singhpratyush fixed this

Comment (singhpratyush) [inline src/org/loklak/objects/MessageEntry.java]: Why wasn't it there earlier?

Have you checked the logs to see if this is working?

Comment (vibhcool) [inline src/org/loklak/objects/MessageEntry.java]: yep, I have tried checking the logs again, this error isn't appearing.

I don't understand
> Why wasn't it there earlier?

Comment (singhpratyush) [inline src/org/loklak/objects/MessageEntry.java]: The `StackOverflow` error wasn't there earlier. Some recent change should've introduced it. I wonder what it was. It would be better to resolve the logic there instead of this.

Comment (vibhcool) [inline src/org/loklak/objects/MessageEntry.java]: yep, it is solved there 😅

**Comment by vibhcool** [comment]
@singhpratyush there is no such error like that,

**Comment by vibhcool** [comment]
the behaviour of UserEntry.java was changed. fixed it

**Comment by vibhcool** [comment]
@Achint08 @djmgit @hemantjadon @kavithaenair @SKrPl @singhpratyush please review
