### PR TITLE
Fixes #1112: Add image, video filter constraints for cache

### LINKED ISSUE #1112: Additional constraints for images,videos not giving results restricted to media
- Issue type: Bug report 

### Short description

Searching for Query /image /audio /video /place , it is expected results to get restricted to tweets which have attached images, audio, video or place.  Searching for http://api.loklak.org/api/search.json?timezoneOffset =-330&q=fossasia+%2Fvideo doesn't give tweets restricted to videos. Same goes for /image.

### PR DESCRIPTION
**Pull request by vibhcool**
### Short description

This PR:-
1) Solves issue #1112.
2) Sync with PR #1164 , to use same ArrayList variable for filter
3) Add filter for get filtered tweets with images , videos or both.

Some tweets with videos doesn't output video links, but has video in that tweet. Issue for this bug has been created as Issue #1171 .

###Examples :-

1) http://localhost:9000/api/search.json?q=video&filter=video,image&source=twitter
2) http://localhost:9000/api/search.json?q=paper&filter=image&source=twitter
3) http://localhost:9000/api/search.json?q=car&filter=video&source=twitter
4) http://localhost:9000/api/search.json?q=video&filter=video,image&source=cache
5) http://localhost:9000/api/search.json?q=paper&filter=image&source=cache
6) http://localhost:9000/api/search.json?q=car&filter=video&source=cache
7) http://localhost:9000/api/search.json?q=video&filter=video,image
8) http://localhost:9000/api/search.json?q=paper&filter=image
9) http://localhost:9000/api/search.json?q=car&filter=video

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by vibhcool** [comment]
Tested and open for review :)

**Comment by singhpratyush** [comment]
@vibhcool: Is the extra `filter` parameter intended here? #1112 says that the search shall be like `fossasia /video`.

**Comment by vibhcool** [comment]
/video and /image doesn't work 
As an example. See this, for keyword image /video , it outputs result matching words image and video:-

screenshot from 2017-05-25 00-34-32

**Comment by singhpratyush** [comment]
@vibhcool: I was not talking about the Twitter search interface. I was referring to the issue description.

It doesn't mention any requirement for the parameter. Maybe @Achint08 can clarify things here.

**Comment by vibhcool** [comment]
It mentions requirement of bug in constraint that work. 
I haven't added filter for audio and location. will fix it. :)

**Comment by Achint08** [comment]
Hey! Somewhere in  this path loklak_server/src/org/loklak/objects/QueryEntry.java , it is mentioned that this is the pattern to search for media restricted results.

**Comment by vibhcool** [comment]
@Achint08 , yep, it is mentioned, but it doesn't output tweets only with images(if you write /image), it also matches the keyword '/image'.

**Comment by Achint08** [comment]
@vibhcool  Sure.  Please go ahead with adding parameters if that solves the issue.

**Comment by vibhcool** [comment]
@Achint08 About the filter for location, location can be set by using `near:"delhi, India" within:<any distance>mi`
for example:-
1) http://loklak.org/api/search.json?q=fossasia%20near:%22delhi,%20India%22%20within:15mi&count=20
2) http://loklak.org/api/search.json?q=fossasia%20near:%22agra,%20India%22&count=20

@singhpratyush @Achint08 
for audio, there doesn't seems to be any audio in tweet posts. there can be live streaming using mixlr, but it doesn't count, does it?

**Comment by vibhcool** [comment]
@Achint08 fixed errors, please re-review

**Comment by vibhcool** [comment]
@kavithaenair , gif images will appear in videos. This problem is not related to this PR.

**Comment by vibhcool** [comment]
@hemantjadon the pr is ready to be merged, just needed to be reviewed 😄

File: src/org/loklak/api/search/SearchServlet.java [hunk 1]
```diff
@@ -150,8 +152,9 @@ protected void doGet(final HttpServletRequest request, final HttpServletResponse
                                     DAO.getConfig(SEARCH_MAX_LOCALHOST_COUNT_NAME, 1000) :
                                     DAO.getConfig(SEARCH_MAX_PUBLIC_COUNT_NAME, 100)));
 
-            String filter = post.get("filter", post.get("filter", ""));
-            
+            String filter = post.get("filter", post.get("filter", "")).replaceAll("\\s","");
```
Comment (singhpratyush) [inline src/org/loklak/api/search/SearchServlet.java]: Isn't the second `post.get(...)` redundant. If you don't get `filter` parameter in the first one, how are you supposed to get in in the second one?

File: src/org/loklak/data/DAO.java [hunk 2]
```diff
@@ -978,6 +987,25 @@ public SearchLocalMessages(final String q, final Timeline.Order order_field, fin
...
+            this(
+                q,
+                order_field,
+                timezoneOffset,
+                resultCount,
+                aggregationLimit,
+                new ArrayList<>(),
+                aggregationFields
+            );
+        }
```
Comment (singhpratyush) [inline src/org/loklak/data/DAO.java]: Please try to use hanging indent here. Refer to `checkstyle` and see if this has to be fixed. Also take a look at other such spots.

File: src/org/loklak/data/DAO.java [hunk 3]
```diff
@@ -933,10 +933,19 @@ public static int deleteOld(IndexName indexName, Date createDateLimit) {
...
+         * @param filterList - list of filters in String datatype
          */
-        public SearchLocalMessages(final String q, final Timeline.Order order_field, final int timezoneOffset, final int resultCount, final int aggregationLimit, final String... aggregationFields) {
+        public SearchLocalMessages (
+                final String q,
+                final Timeline.Order order_field,
+                final int timezoneOffset,
+                final int resultCount,
+                final int aggregationLimit,
+                final ArrayList<String> filterList,
```
Comment (singhpratyush) [inline src/org/loklak/data/DAO.java]: Wouldn't it be better to use more generic `List` instead of `ArrayList`? We may wish to use something other than `ArrayList` in future.

Comment (vibhcool) [inline src/org/loklak/data/DAO.java]: using List is giving error, 
```
error: incompatible types: List<String> cannot be converted to ArrayList<String>
```

Comment (singhpratyush) [inline src/org/loklak/data/DAO.java]: Yes, `List` can't be converted to `ArrayList`. It's the other way round, as `ArrayList` is derived from `List`. I was talking about something like this - 
```java
List<String> someThing(List<String> list) {
    ArrayList<String> aList = (ArrayList) list;
    ...  // Do whatever needed
    return aList;
}
```

Comment (vibhcool) [inline src/org/loklak/data/DAO.java]: yes, on storing object of ArrayList in List variable, I got above error

File: src/org/loklak/data/DAO.java (hunk 2 above)
Comment (vibhcool) [inline src/org/loklak/data/DAO.java]: I referred checkstyle and fixed errors related to this PR.

File: src/org/loklak/api/search/SearchServlet.java (hunk 1 above)
Comment (vibhcool) [inline src/org/loklak/api/search/SearchServlet.java]: this was a silly mistake, fixed this 😅

**Comment by vibhcool** [comment]
@singhpratyush please re-review, fixed all the errors :)

File: src/org/loklak/api/search/SearchServlet.java [hunk 4]
```diff
@@ -22,10 +22,12 @@
 import java.io.IOException;
 import java.io.PrintWriter;
 import java.net.URLEncoder;
+import java.util.ArrayList;
+import java.util.Arrays;
+import java.util.concurrent.atomic.AtomicLong;
+import java.util.concurrent.atomic.AtomicInteger;
```
Comment (singhpratyush) [inline src/org/loklak/api/search/SearchServlet.java]: I think this order is still incorrect.

File: src/org/loklak/data/DAO.java (hunk 2 above)
Comment (singhpratyush) [inline src/org/loklak/data/DAO.java]: Can you accommodate theses variables in a single line? The allowable line length is enough to support this. Also, it will be consistent with other parts of the project. There are many other such changes in this PR.

File: src/org/loklak/api/search/SearchServlet.java (hunk 4 above)
Comment (vibhcool) [inline src/org/loklak/api/search/SearchServlet.java]: fixed this 😅

File: src/org/loklak/data/DAO.java (hunk 2 above)
Comment (vibhcool) [inline src/org/loklak/data/DAO.java]: @singhpratyush This is very long when accomodated in one line, this indentation is to improves readibility. 
Don't you think it is more readable now?

Comment (singhpratyush) [inline src/org/loklak/data/DAO.java]: It is indeed more readable, but it can be like this too - 
```java
this(q, orderField, timezoneOffset, resultCount, aggregationLimit,
    new ArrayList<>(), aggregationFields);
```

Again, it is all about personal taste. So, according to me, it is better to stick to the current conventions of the project.

**Comment by vibhcool** [comment]
@SarishiNoHara , added the suggested changes :)
