### PR TITLE
Fixes #1478: Unused variables in Scrapers

### LINKED ISSUE #1478: Unused variables in Scrapers
- Issue type: Bug report

Issues: 

1) Some unused variables are existing. They shall be removed to keep the code clean.
2) Unused variable in YoutubeScraper
3) Very high value of timeout in ScrapeLoklak method in DAO for thread.

### PR DESCRIPTION
**Pull request by vibhcool**
This PR fixes Issue #1478

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by vibhcool** [comment]
@djmgit @kavithaenair @vibhcool @Achint08 @hemantjadon @SKrPl @singhpratyush : Please review

File: src/org/loklak/data/DAO.java [hunk 1]
```diff
@@ -1261,7 +1261,7 @@ public static JSONArray scrapeLoklak(
         } finally {
             scraperRunner.shutdown();
             try {
-                scraperRunner.awaitTermination(24L, TimeUnit.HOURS);
+                scraperRunner.awaitTermination(3000L, TimeUnit.SECONDS);
```
Comment (singhpratyush) [inline src/org/loklak/data/DAO.java]: Why this change?

Comment (vibhcool) [inline src/org/loklak/data/DAO.java]: old value of running the thread is in hours 😅 . We can't run a thread for hours
