### PR TITLE
Fixes #1537: Build issue on development branch

### LINKED ISSUE #1537: Build issue on development branch
- Issue type: Bug report

Issue is related to failure of test for ClientConnection.java

Check the TravisCI build logs https://travis-ci.org/loklak/loklak_server/builds/276787688#L839

### PR DESCRIPTION
**Pull request by vibhcool**
Fixes Build error in development branch

This PR replaces the redirect link as previous links redirected multiple times

### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by vibhcool** [comment]
The last url link has multiple redirects. So i used the existing tinyurl link  from [RedirectUnshortenerTest.java](https://github.com/loklak/loklak_server/blob/0f055ea6d2d768ea13b29c6fee20ab95902d70ab/test/org/loklak/harvester/RedirectUnshortenerTest.java#L18) . This tinyurl link is being tested in that test for testing the redirecting services.

File: test/org/loklak/http/ClientConnectionTest.java [hunk 1]
```diff
@@ -12,7 +12,7 @@
     public void metaUrlExtractorTest() throws IOException {
         HashMap<String, String> linkMap = new HashMap<>();
 
-        linkMap.put("http://yacy.net", "http://yacy.net/en/index.html");
+        linkMap.put("http://tinyurl.com/loklak-server", "https://github.com/loklak/loklak_server/wiki");
```
Comment (singhpratyush) [inline test/org/loklak/http/ClientConnectionTest.java]: The test is for checking redirects from meta tag present on a webpage and not for `301` response codes. We need to check this with something similar.
